/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintproject;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSlider;

/**
 *
 * @author kdani
 */
public class Paint extends javax.swing.JFrame {
    

    private Draw canvas;
    /**
     * Creates new form Paint
     */
    public Paint() {
        initComponents();
        
        squareButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //start drawing sqaures
                canvas.brush=false;
                canvas.circle=false;
                canvas.rectangle=true;
            }
        });
        
        circleButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //start drawing sqaures
                canvas.brush=false;
                canvas.rectangle=false;
                canvas.circle=true;
            }
        });
        
        
        canvas = new Draw();
        canvas.setBounds(5,5,1140,750);
        canvas.addMouseListener(new java.awt.event.MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                
            }

            @Override
            public void mousePressed(MouseEvent e) {
               canvas.mousePressed(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                canvas.mouseReleased(e);

            }

            @Override
            public void mouseEntered(MouseEvent e) {}

            @Override
            public void mouseExited(MouseEvent e) {}
            
        });        
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionListener(){

            @Override
            public void mouseDragged(MouseEvent e) {
                canvas.mouseReleased(e);
            }

            @Override
            public void mouseMoved(MouseEvent e) {}
            
        });
        this.add(canvas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paintMenu = new javax.swing.JMenuBar();
        brushButton = new javax.swing.JMenu();
        shapesButton = new javax.swing.JMenu();
        triangleButton = new javax.swing.JMenuItem();
        circleButton = new javax.swing.JMenuItem();
        squareButton = new javax.swing.JMenuItem();
        pickColorButton = new javax.swing.JMenu();
        strokeButton = new javax.swing.JMenu();
        eraserButton = new javax.swing.JMenu();
        imageButton = new javax.swing.JMenu();
        saveButton = new javax.swing.JMenu();
        fileButton = new javax.swing.JMenu();
        newButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paintMenu.setBackground(new java.awt.Color(0, 102, 255));

        brushButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/paintButton.png"))); // NOI18N
        brushButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brush(evt);
            }
        });
        paintMenu.add(brushButton);

        shapesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/shapesButton.png"))); // NOI18N

        triangleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/triangleButton.png"))); // NOI18N
        triangleButton.setText("Triangle");
        shapesButton.add(triangleButton);

        circleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/circleButton.png"))); // NOI18N
        circleButton.setText("Circle");
        shapesButton.add(circleButton);

        squareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/squareButton.png"))); // NOI18N
        squareButton.setText("Square");
        shapesButton.add(squareButton);

        paintMenu.add(shapesButton);

        pickColorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/colorButton.png"))); // NOI18N
        pickColorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pickColor(evt);
            }
        });
        paintMenu.add(pickColorButton);

        strokeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/strokeButton.png"))); // NOI18N
        strokeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeStroke(evt);
            }
        });
        paintMenu.add(strokeButton);

        eraserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/eraserButton.png"))); // NOI18N
        eraserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eraser(evt);
            }
        });
        paintMenu.add(eraserButton);

        imageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/imageButton.png"))); // NOI18N
        paintMenu.add(imageButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/saveButton.png"))); // NOI18N
        paintMenu.add(saveButton);

        fileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/open.png"))); // NOI18N
        paintMenu.add(fileButton);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/newButton.png"))); // NOI18N
        paintMenu.add(newButton);

        setJMenuBar(paintMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brush(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brush

        // TODO add your handling code here:

        //start drawing lines
        canvas.circle=false;
        canvas.rectangle=false;
        canvas.brush=true;
    }//GEN-LAST:event_brush

    private void pickColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pickColor
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(canvas,"Choose a color", Color.white);
        System.out.println("The selected color was:" + color);
        canvas.changeColor(color);
        
    }//GEN-LAST:event_pickColor

    private void changeStroke(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeStroke
        // TODO add your handling code here:
                JSlider strokeSelector = new JSlider(2,20);
        JPanel sliderHolder= new JPanel();
        sliderHolder.add(strokeSelector);
        
        int response = JOptionPane.showOptionDialog
            (this,                  // I'm within a JFrame here
             sliderHolder,
             "Select Stroke",
             JOptionPane.OK_CANCEL_OPTION,
             JOptionPane.INFORMATION_MESSAGE,
             null, null, null
            );
        int stroke;
        if (JOptionPane.OK_OPTION == response) 
         { stroke = strokeSelector.getValue(); }
        else { stroke = 0; }
        System.out.println(stroke);
        
        
        canvas.changeStroke(stroke);
    }//GEN-LAST:event_changeStroke

    private void eraser(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eraser
        // TODO add your handling code here:
        canvas.changeColor(Color.WHITE);
        
    }//GEN-LAST:event_eraser

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paint().setVisible(true);
            }
        });
    }
    
    public void paint (Graphics g){
        super.paint(g);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu brushButton;
    private javax.swing.JMenuItem circleButton;
    private javax.swing.JMenu eraserButton;
    private javax.swing.JMenu fileButton;
    private javax.swing.JMenu imageButton;
    private javax.swing.JMenu newButton;
    private javax.swing.JMenuBar paintMenu;
    private javax.swing.JMenu pickColorButton;
    private javax.swing.JMenu saveButton;
    private javax.swing.JMenu shapesButton;
    private javax.swing.JMenuItem squareButton;
    private javax.swing.JMenu strokeButton;
    private javax.swing.JMenuItem triangleButton;
    // End of variables declaration//GEN-END:variables
}
